canonical/dex-auth-operator

src/charm.py
Dex is unable to do automatic namespace discovery on kubernetes 1.21 so we help it with this env variable.
Workaround for this mentioned [here](https://github.com/dexidp/dex/issues/2082#issuecomment-818124478).
=> Fix dex-auth on 1.21

src/charm.py, tests/unit/test_charm.py
The leader elected flag causes eternal restarts and isn't actually
needed.
The rewrite field in the ingress relation was wrongly set and cause the
dashboard to never show up.
=> Remove Leader Elected and Fix Ingress Rewrite

tests/integration/test_upgrade_charm.py
This will deploy the previous charm in the charmstore and try to upgrade it with a locally build charm with the latest charms.
Depends on this PR: https://github.com/juju/python-libjuju/pull/507
=> Add Upgrade test

.github/workflows/publish.yaml
Publishes to `latest/edge` if branch name is `master` or `main`. Publishes to parsed branch name otherwise.
=> Add track-based publishing

requirements.txt, src/charm.py, src/manifests/config-map.yaml, src/manifests/deployment.yaml, src/manifests/roles.yaml, src/manifests/service.yaml, test-requirements.txt, tests/unit/test_charm.py
ServiceAccount used for dex-auth was missing a `automountServiceAccountToken: true`, which resulted in the workload pod not having access to the service account and thus the workload going into a crash loop.  This was visible in the pod logs which included `msg="config issuer: /dex" failed to initialize storage: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`.  This broken pod was not detected by CI because the charm did not check whether deployments/statefulsets actually had their pods up and running.
Fixes committed here:
* `automountServiceAccountToken: true` added to the ServiceAccount for dex-auth to enable passing a ServiceAccount token to the workload pods
* some checks during install that attempt to validate that the deployments/statefulsets we …
=> fix: missing ServiceAccount token, status handling

.github/workflows/publish.yaml, src/charm.py
Ingress information is not send correctly due to events not being triggered correctly. to avoid this we are moving send_info to main to ensure ingress information is always sent.
=> Move send info to main

metadata.yaml, src/charm.py, test-requirements.txt, tests/integration/test_charm.py
Update of [merged prometheus-grafana integration PR](https://github.com/canonical/dex-auth-operator/pull/47) according to latest Observability Team's review: removed the direct relation between prometheus and dex-auth.
=> Removed prometheus-app direct relation in test

tests/integration/test_charm.py
Fixes #58 
PASSED
------------------------------------------------------------------------------------------- live log teardown -------------------------------------------------------------------------------------------
INFO     pytest_operator.plugin:plugin.py:768 Model status:
Model            Controller  Cloud/Region        Version  SLA          Timestamp
test-charm-4485  controller  microk8s/localhost  2.9.31   unsupported  03:12:40Z
App                           Version                Status  Scale  Charm                         Channel     Rev  Address         Exposed  Message
dex-auth                                             active      1  dex-auth                                    0  10.152.183.230  no
grafana-k8s                                          active      1 …
=> trust prometheus and grafana in integration tests

.github/workflows/integration.yaml, test-requirements.txt
This PR updates microk8s version in CI from 1.21 to 1.22.
=> CI: Update microk8s from 1.21 to 1.22

metadata.yaml, tests/integration/test_charm.py
This vendors all remotely defined serialized-data-interface schemas, embedding them in the respective metadata.yaml(s) rather than storing them as a remote link.  This is to enable offline deployment of the charms, as described in [jira](https://warthogs.atlassian.net/browse/KF-727?atlOrigin=eyJpIjoiN2JjZTdlMGYxNDQ3NDdlYzljZDQxNDQ1MTk0OTdkNTEiLCJwIjoiaiJ9).
=> feat: localize SDI schemas

metadata.yaml
These links in the charm's metadata will be rendered in charmhub.io to get access to relevant information/docs.
=> docs: add documentation links to metadata.yaml

requirements-integration.in
pin python-libjuju<3.1 to avoid unsupported version errors
the juju agent 2.9.34 is not compatible with pythonlib-juju 3.1, causing the following error:
`juju.errors.JujuConnectionError: juju server-version 2.9.34 not supported`
To avoid this, we have to pin to a version below 3.1.
=> tests: pin python-libjuju<3.1

src/prometheus_alert_rules/unit_unavailable.rule
As stated in issue https://github.com/canonical/bundle-kubeflow/issues/564 the duation for alerts for argo is set to 0m, which is too low for prod environments. We need to change to at least 5m to prevent the flapping behavior.
Partial-Bug: https://github.com/canonical/bundle-kubeflow/issues/564
=> Changed unit_unavailable interval for prometheus

src/charm.py
Currently, Dex Charm is doing apt install. Update this logic to ensure the Dex Charm can work in an air-gapped environment
Closes https://github.com/canonical/dex-auth-operator/issues/100
=> feat: Remove apt-install from Dex Charm

requirements-integration.in
Pin Selenium version to `<4.11` in charm's integration tests because upgrading to `4.11.2` results in the following issue https://github.com/canonical/dex-auth-operator/issues/151. 
Related runs 
https://github.com/canonical/dex-auth-operator/actions/runs/5763096636/job/15669866245?pr=132#step:5:2253
https://github.com/canonical/dex-auth-operator/actions/runs/5763096636/job/15627005664?pr=132#step:5:2066
=> requirements: Pin selenium version to 4.10.x

charmcraft.yaml, requirements.in, requirements.txt, src/charm.py, tests/integration/test_charm.py
This PR cherry picks 4e42ce3853135ee8fdf2829f10553442c2c86bf6, partially cherry-picks a716963, and makes changes to the requirements.* files so that dex-auth can be deployed in an airgap environment. These changes are mirroring in `track/2.31` what we currently have in `main`.
Fixes #167
=> feat: make charm work on airgap environments

tests/integration/test_charm.py
refactors the integration test CI to:
* use the latest/edge version of oidc-gatekeeper
* provide oidc-gatekeeper with the public-url config during setup rather than during web browsing.  This is required because the oidc-gatekeeper v1.7+ will block the charm without this setting, and also because it makes more sense then changing oidc-gatekeeper settings in the fixture for a later test
Context: previously, the integration tests here incorrectly pinned OIDC to that from charmed kubeflow 1.4, which is not how we want our main branch testing to work.
=> fix integration tests for OIDC in Charmed Kubeflow 1.7+

tests/integration/test_charm.py
* cherry-picks a fix for the integration tests from main, enabling using OIDC versions of 1.7+
* pins integration tests dependencies to the versions required for this release, not latest/stable
=> fix integration tests in track/2.31

tests/integration/test_charm.py
* cherry-picks a fix for the integration tests from main, enabling using OIDC versions of 1.7+
* pins integration tests dependencies to the versions required for this release, not latest/stable
=> fix integration tests in track/2.36

metadata.yaml, tests/integration/test_charm.py
uses rock built from https://github.com/canonical/dex-auth-rocks/blob/track/2.31.2/dex/rockcraft.yaml
merge after #176
closes #173
=> use rock in `track/2.31`

metadata.yaml, tests/integration/test_charm.py
Updates the dex image to use `charmedkubeflow/dex:2.36.0-f262d95`, which is built from [dex-auth-rocks](https://github.com/canonical/dex-auth-rocks)
=> Update dex image to pull from Canonical-built source

metadata.yaml
Updates the dex image to use `charmedkubeflow/dex:2.36.0-f262d95`, which is built from [dex-auth-rocks](https://github.com/canonical/dex-auth-rocks)
=> Update `track/2.36` dex image to pull from Canonical-built source

lib/charms/observability_libs/v1/kubernetes_service_patch.py, src/charm.py, tests/integration/test_charm.py, tests/unit/test_charm.py
This commit ensures the configuration value for the telemetry setting is correctly passed to the workload configuration value. With this we ensure the workload is correctly exposing metrics in the desired endpoint so they can be scraped by prometheus. With this change we also must ensure that the K8s Service correctly exposes the ports of the endpoints that this workload has (for metrics and the actual dex service). Finally, a bit of refactoring work had to be made in the unit test to match the recent changes and the kubernetes_service_patch library this charm uses has been bumped v0 -> v1.
Part of canonical/bundle-kubeflow#563
Please refer to the steps to reproduce in [this comment](https://github.com/canonical/bundle-kubeflow/issues/564#issuecomment-1925538870), just deploying this app. …
=> fix: set telemetry config value, patch service, update tests

lib/charms/observability_libs/v1/kubernetes_service_patch.py, src/charm.py, tests/integration/test_charm.py, tests/unit/test_charm.py
* fix: set telemetry config value, patch service, update tests
This commit ensures the configuration value for the telemetry setting is correctly passed to the workload configuration value. With this we ensure the workload is correctly exposing metrics in the desired endpoint so they can be scraped by prometheus. With this change we also must ensure that the K8s Service correctly exposes the ports of the endpoints that this workload has (for metrics and the actual dex service). Finally, a bit of refactoring work had to be made in the unit test to match the recent changes and the kubernetes_service_patch library this charm uses has been bumped v0 -> v1.
Part of canonical/bundle-kubeflow#563
* tests: add an assertion for checking unit is available
The test_prometheus_grafana_integration …
=> fix: set telemetry config value, patch service, update tests (#185)

metadata.yaml
closes: https://github.com/canonical/dex-auth-operator/issues/192
Using the upstream `v2.39.1` image.
=> Change image to v2.39.1

.github/workflows/integrate.yaml
Part of canonical/bundle-kubeflow#944
=> ci: use juju 3.4/stable instead of 3.5/stable in track 2.36

lib/charms/dex_auth/v0/dex_oidc_config.py, lib/charms/harness_extensions/v0/capture_events.py, requirements-unit.txt, requirements.in, requirements.txt, tests/unit/test_dex_oidc_config.py
Add a library to handle the dex-oidc-config relation interface. This library allows dex-auth to share its OIDC configuration with OIDC clients such as the oidc-gatekeeper charm. The library is designed to be extended to share any information about Dex, but right now it is only sharing Dex's issuer url.
Closes #203
1. Deploy the charm from this PR
2. Deploy the charm from https://github.com/canonical/oidc-gatekeeper-operator/pull/163
3. Wait for them to become active and idle
4. Add the relation between them (interface dex-oidc-config)
5. Verify that the requirer is actually getting data from dex-auth `juju show-unit oidc-gatekeeper`. There should be the `dex-issuer-url` value.
=> feat: add dex_oidc_config library

config.yaml, src/charm.py, tests/unit/test_charm.py
Since this is a breaking change, it is preferrable to keep some sort of compatibility that allow users with existing deployments to keep running Dex even after the upgrade. This configuration option can be removed after a deprecation notice is rolled out.
1. Deploy dex-auth from 2.36/stable
2. Configure `public-url` with any value `juju config dex-auth public-url="my-known-value.io"
3. Verify this value is populated in Dex's OIDC configuration:
```
curl -v <dex's svc>:5556/dex/.well-known/openid-configuration
{
"issuer": "my-known-value.io/dex",
...
```
4. Refresh dex-auth to the charm from this PR
5. Without changing the charm configuration, make sure that Dex's OIDC configuration persists
```
curl -v <dex's svc>:5556/dex/.well-known/openid-configuration
{
"issuer": …
```
=> chore: keep public-url config option for compatibility

charmcraft.yaml, config.yaml, lib/charms/dex_auth/v0/dex_oidc_config.py, lib/charms/harness_extensions/v0/capture_events.py, metadata.yaml, requirements-unit.txt, requirements.in, requirements.txt, src/charm.py, tests/integration/test_charm.py, tests/unit/test_charm.py, tests/unit/test_dex_oidc_config.py
This PR introduces the following changes in `main`:
* refactor: add dex-issuer-url and remove public-url config options (#209)
* feat: add dex_oidc_config library (#208)
* chore: keep public-url config option for compatibility #213 
These changes were already tested in their individual PRs.
=> feat: merge KF-5526-issuer-url-dev-branch into main

src/charm.py
This will allow the library to handle relation data during config changed events.
=> fix: add config_changed as refresh event for dex-oidc-config provider

.github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
=> ci(upload-charm): use charmcraft from latest/candidate in track/2.39

.github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
=> ci(upload-charm): use charmcraft from latest/candidate in track/2.36

.github/workflows/integrate.yaml, .gitignore, terraform/README.md, terraform/main.tf, terraform/outputs.tf, terraform/variables.tf, terraform/versions.tf, tox.ini
This commit adds the terraform/ directory to the root of the repository to host the Terraform module of this charm. This follows the standard set in CC006. For more information please also refer to canonical/argo-operators/pull/198.
Part of #226
1. Check the correctness of the module with `tox -e tflint`
2. Apply with `terraform apply -var "channel=latest/edge" -var "model_name=kubeflow" --auto-approve`
3. Wait for the charm to be deployed.
This module must expose all the information in the `metadata.yaml` of this charm, make sure you review it by comparing that file to the Tf files in this PR.
=> feat: add Terraform module for dex-auth

.github/workflows/integrate.yaml, .github/workflows/publish.yaml, .github/workflows/release.yaml
Closes https://warthogs.atlassian.net/browse/KF-7137, #246 
This PR updates the CI to use `24.04`:
- We also use `setup-python` to use `3.8`
- We set `desctructive-mode` to false since we're now building on a different base that the one we are on
=> chore: Update CI to use 24.04

.github/workflows/integrate.yaml
The reason for this downgrade is that `v5.4.0` of the action doesn't actually test the setup of Python version `3.8.0`. See https://github.com/canonical/notebook-operators/pull/443#discussion_r1991435614 for more details
=> chore: Downgrade setup-python action to 5.3.0

.gitignore, src/charm.py, tests/unit/test_charm.py
This PR backports #280 to the `track/2.41` branch.
=> backport: Catch `pebble.ChangeError` when restarting the workload container
